# Use CircleCI version 2.1 
version: 2.1
# Add the orbs stanza below your version, invoking the orb:
orbs:
  docker: circleci/docker@2.2.0
# Use docker elements in workflows (sesuai ketentuan untuk branch karsajobs) and jobs
workflows:
  lint-dockerfile:
    # Use hadolint to lint a Dockerfile
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile

  test-app:
    jobs:
      - test-app

  build-app-karsajobs:
    jobs:
      - build-app-karsajobs


jobs:
  # Build and push an image from bash script, get variable from project setting - environment
  build-app-karsajobs:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 
          command: |
            . build_push_image_karsajobs.sh
  # This image can be used with the CircleCI docker executor, jalankan unit test untuk backend.
  test-app:
    docker:
      - image: cimg/go:1.20.2
    steps:
      - checkout
      - run:
          command: |
            go test -v -short --count=1 $(go list ./...)